#ifndef PRIORITIES_H_INCLUDED
#define PRIORITIES_H_INCLUDED

#define TASK_BOOTSTRAP_PRIORITY         1
#define TASK_KEYSCAN_PRIORITY           3
#define TASK_IRQ_EVENT_PRIORITY			3
#define TASK_GUI_PRIORITY               2
#define TASK_BGLIGHT_PRIORITY           4

#endif /* PRIORITIES_H_INCLUDED */
