#ifndef SCREEN_FLASHROM_TASK_H
#define SCREEN_FLASHROM_TASK_H

#include <HMI_Engine.h>

typedef enum{
	FLASHROM_PROGRESS_BAR_WAIT  = 0,
	FLASHROM_PROGRESS_BAR_READ  = 1,
	FLASHROM_PROGRESS_BAR_WRITE = 2
} FLASHROM_PROGRESS_BAR_TYPE;

typedef struct{
	FLASHROM_PROGRESS_BAR_TYPE eProgressBarType;
	uint32_t uiBytesTotal;
} FLASHROM_PBAR_SETUP_EVENT_DATA;

HMI_EVENT_TYPE_DECLARE(FLASHROM_LOCK_EVENT,uint8_t);
HMI_EVENT_TYPE_DECLARE(FLASHROM_PBAR_SETUP_EVENT,FLASHROM_PBAR_SETUP_EVENT_DATA);
HMI_EVENT_TYPE_DECLARE(FLASHROM_PBAR_UPDATE_EVENT,uint32_t);

void flashRomTask(void);

#endif
